/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant_chef_app.view;

import java.util.List;
import javax.swing.JOptionPane;
import restaurant_chef_app.Controller.*;
import restaurant_chef_app.clases.*;

/**
 *
 * @author PC PERSONAL
 */
public class CrearCocinero extends javax.swing.JFrame {

    /**
     * Creates new form CrearCocinero
     */
    public CrearCocinero() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_idCocinero = new javax.swing.JTextField();
        txt_NombreCocinero = new javax.swing.JTextField();
        txt_passwCocinero = new javax.swing.JTextField();
        btn_CrearCocinero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(233, 236, 239));

        jPanel2.setBackground(new java.awt.Color(19, 70, 134));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 244, 227));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREAR COCINERO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        txt_idCocinero.setBackground(new java.awt.Color(254, 178, 26));
        txt_idCocinero.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        txt_idCocinero.setForeground(new java.awt.Color(253, 244, 227));
        txt_idCocinero.setText("ID");
        txt_idCocinero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_idCocineroMouseClicked(evt);
            }
        });

        txt_NombreCocinero.setBackground(new java.awt.Color(254, 178, 26));
        txt_NombreCocinero.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        txt_NombreCocinero.setForeground(new java.awt.Color(253, 244, 227));
        txt_NombreCocinero.setText("NOMBRE");
        txt_NombreCocinero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_NombreCocineroMouseClicked(evt);
            }
        });

        txt_passwCocinero.setBackground(new java.awt.Color(254, 178, 26));
        txt_passwCocinero.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        txt_passwCocinero.setForeground(new java.awt.Color(253, 244, 227));
        txt_passwCocinero.setText("CONTRASEÑA");
        txt_passwCocinero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_passwCocineroMouseClicked(evt);
            }
        });

        btn_CrearCocinero.setBackground(new java.awt.Color(237, 63, 39));
        btn_CrearCocinero.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_CrearCocinero.setForeground(new java.awt.Color(254, 178, 26));
        btn_CrearCocinero.setText("REGISTRAR");
        btn_CrearCocinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearCocineroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_idCocinero, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_NombreCocinero, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_passwCocinero, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_CrearCocinero)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_idCocinero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_NombreCocinero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_passwCocinero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_CrearCocinero, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idCocineroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_idCocineroMouseClicked
        // TODO add your handling code here:
        if (txt_idCocinero.getText().equals("ID")) {
            txt_idCocinero.setText("");
        }
        if (txt_NombreCocinero.getText().isEmpty()) {
            txt_NombreCocinero.setText("NOMBRE");
        }
        if (txt_passwCocinero.getText().isEmpty()) {
            txt_passwCocinero.setText("CONTRASEÑA");
        }
    }//GEN-LAST:event_txt_idCocineroMouseClicked

    private void txt_NombreCocineroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_NombreCocineroMouseClicked
        // TODO add your handling code here:
        if (txt_idCocinero.getText().isEmpty()) {
            txt_idCocinero.setText("ID");
        }
        if (txt_NombreCocinero.getText().equals("NOMBRE")) {
            txt_NombreCocinero.setText("");
        }
        if (txt_passwCocinero.getText().isEmpty()) {
            txt_passwCocinero.setText("CONTRASEÑA");
        }
    }//GEN-LAST:event_txt_NombreCocineroMouseClicked

    private void txt_passwCocineroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passwCocineroMouseClicked
        // TODO add your handling code here:
        if (txt_idCocinero.getText().isEmpty()) {
            txt_idCocinero.setText("ID");
        }
        if (txt_NombreCocinero.getText().isEmpty()) {
            txt_NombreCocinero.setText("NOMBRE");
        }
        if (txt_passwCocinero.getText().equals("CONTRASEÑA")) {
            txt_passwCocinero.setText("");
        }
    }//GEN-LAST:event_txt_passwCocineroMouseClicked

    private void btn_CrearCocineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearCocineroActionPerformed
        // TODO add your handling code here:
        String id = txt_idCocinero.getText().trim();
        String nombre = txt_NombreCocinero.getText().trim();
        String contraseña = txt_passwCocinero.getText().trim();
        List<Cocinero> usuarios = CocineroController.leerCocinero();

        boolean credencialesValidas = CocineroController.validarCocineroRegistrado(id);
        if (credencialesValidas) {
            JOptionPane.showMessageDialog(this, "Usario ya existe!!!", "Error de creacion", JOptionPane.ERROR_MESSAGE);
        } else {
            CocineroController.CrearUsuariosCocinero(usuarios, id, nombre, contraseña);
            JOptionPane.showMessageDialog(this, "Usuario creado", "Usuario Creado", JOptionPane.INFORMATION_MESSAGE);

            dispose();
        }
    }//GEN-LAST:event_btn_CrearCocineroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCocinero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCocinero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCocinero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCocinero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCocinero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CrearCocinero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_NombreCocinero;
    private javax.swing.JTextField txt_idCocinero;
    private javax.swing.JTextField txt_passwCocinero;
    // End of variables declaration//GEN-END:variables
}
