/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant_chef_app.view;

import java.util.*;
import javax.swing.*;
import restaurant_chef_app.clases.*;

/**
 *
 * @author Sebastian
 */
public class Crear_propietario extends javax.swing.JFrame {

    /**
     * Creates new form Crear_propietario
     */
    public Crear_propietario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txt_passwPropietario = new javax.swing.JTextField();
        txt_idPropietario = new javax.swing.JTextField();
        txt_NombrePropietario = new javax.swing.JTextField();
        btn_CrearPropietario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_volver = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(231, 245, 245));

        jPanel3.setBackground(new java.awt.Color(19, 70, 134));

        txt_passwPropietario.setBackground(new java.awt.Color(254, 178, 26));
        txt_passwPropietario.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        txt_passwPropietario.setForeground(new java.awt.Color(253, 244, 227));
        txt_passwPropietario.setText("CONTRASEÑA");
        txt_passwPropietario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_passwPropietarioMouseClicked(evt);
            }
        });

        txt_idPropietario.setBackground(new java.awt.Color(254, 178, 26));
        txt_idPropietario.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        txt_idPropietario.setForeground(new java.awt.Color(253, 244, 227));
        txt_idPropietario.setText("ID");
        txt_idPropietario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_idPropietarioMouseClicked(evt);
            }
        });

        txt_NombrePropietario.setBackground(new java.awt.Color(254, 178, 26));
        txt_NombrePropietario.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        txt_NombrePropietario.setForeground(new java.awt.Color(253, 244, 227));
        txt_NombrePropietario.setText("NOMBRE");
        txt_NombrePropietario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_NombrePropietarioMouseClicked(evt);
            }
        });

        btn_CrearPropietario.setBackground(new java.awt.Color(237, 63, 39));
        btn_CrearPropietario.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_CrearPropietario.setForeground(new java.awt.Color(254, 178, 26));
        btn_CrearPropietario.setText("REGISTRAR");
        btn_CrearPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearPropietarioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 244, 227));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREAR PROPIETARIO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_CrearPropietario)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_idPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_passwPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_NombrePropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_idPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(txt_NombrePropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(txt_passwPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(btn_CrearPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(253, 244, 227));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant_chef_app/img/propietario.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(237, 63, 39));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("propietario");

        btn_volver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant_chef_app/img/devolver.png"))); // NOI18N
        btn_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_volverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(120, 120, 120))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 5, 1000, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CrearPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearPropietarioActionPerformed
        // TODO add your handling code here:
        String id = txt_idPropietario.getText().trim();
        String nombre = txt_NombrePropietario.getText().trim();
        String contraseña = txt_passwPropietario.getText().trim();
        List<Propietario> usuarios = ArchivoManager.leerPropietarios();

        // Validar campos vacíos
        if (id.isEmpty() || nombre.isEmpty() || contraseña.isEmpty()
            || id.equals("ID") || nombre.equals("NOMBRE") || contraseña.equals("CONTRASEÑA")) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que el ID sea solo números
        if (!id.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "El ID solo debe contener números", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que el nombre NO sea números
        if (nombre.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "El nombre no puede contener solo números", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar si el usuario ya existe
        boolean usuarioExiste = ArchivoManager.validarUsuarioRegistrado(id);

        if (usuarioExiste) {
            JOptionPane.showMessageDialog(this, "El usuario ya existe", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear usuario
        ArchivoManager.CrearUsuariosPropietario(usuarios, id, nombre, contraseña);
        JOptionPane.showMessageDialog(this, "Usuario creado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        // Abrir la ventana del propietario
        new VentanaPropietario(nombre).setVisible(true);
        dispose();

    }//GEN-LAST:event_btn_CrearPropietarioActionPerformed

    private void btn_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_volverMouseClicked
        // TODO add your handling code here:
        new inicio().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_volverMouseClicked

    private void txt_idPropietarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_idPropietarioMouseClicked
        if (txt_idPropietario.getText().equals("ID")) {
            txt_idPropietario.setText("");
        }
        if (txt_NombrePropietario.getText().isEmpty()) {
            txt_NombrePropietario.setText("NOMBRE");
        }
        if (txt_passwPropietario.getText().isEmpty()) {
            txt_passwPropietario.setText("CONTRASEÑA");
        }
    }//GEN-LAST:event_txt_idPropietarioMouseClicked

    private void txt_NombrePropietarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_NombrePropietarioMouseClicked
        if (txt_idPropietario.getText().isEmpty()) {
            txt_idPropietario.setText("ID");
        }
        if (txt_NombrePropietario.getText().equals("NOMBRE")) {
            txt_NombrePropietario.setText("");
        }
        if (txt_passwPropietario.getText().isEmpty()) {
            txt_passwPropietario.setText("CONTRASEÑA");
        }
    }//GEN-LAST:event_txt_NombrePropietarioMouseClicked

    private void txt_passwPropietarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passwPropietarioMouseClicked
        if (txt_idPropietario.getText().isEmpty()) {
            txt_idPropietario.setText("ID");
        }
        if (txt_NombrePropietario.getText().isEmpty()) {
            txt_NombrePropietario.setText("NOMBRE");
        }
        if (txt_passwPropietario.getText().equals("CONTRASEÑA")) {
            txt_passwPropietario.setText("");
        }
    }//GEN-LAST:event_txt_passwPropietarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crear_propietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crear_propietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crear_propietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crear_propietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crear_propietario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CrearPropietario;
    private javax.swing.JLabel btn_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt_NombrePropietario;
    private javax.swing.JTextField txt_idPropietario;
    private javax.swing.JTextField txt_passwPropietario;
    // End of variables declaration//GEN-END:variables
}
