package restaurant_chef_app.view;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import restaurant_chef_app.Controller.*;
import restaurant_chef_app.clases.*;


public class TomarPedidos extends javax.swing.JFrame {
    DefaultListModel<String> modeloCarrito = new DefaultListModel<>();
    public List<Pedido> listaPedidos;
    public Empleado empleado;
    

    public TomarPedidos(Empleado empleado) {
        initComponents();
        setLocationRelativeTo(null);
        this.empleado = empleado;
         jListCarrito.setModel(modeloCarrito);
        
        String nuevoId = PedidoController.generarNuevoId();
        txt_IdPedido.setText(nuevoId);
        txt_IdPedido.setEnabled(false); 


        List<Platillo> menu = PlatilloController.obtenerPlatillosDisponibles();
        DefaultListModel<String> modelo = new DefaultListModel<>();

        String categoriaActual = "";

        for (Platillo p : menu) {
           
            modelo.addElement("• " + p.getNombre() + " ($" + p.getPrecio() + ")"  + p.getCategoria()+ ")");
        }

        listaPlatillos.setModel(modelo);
        listaPedidos = PedidoController.cargarPedidos();
    }

    private void enviarPedido() {
        String id = txt_IdPedido.getText();
        String nombre = txtNombreCliente.getText();
        List<String> platillosSeleccionados = listaPlatillos.getSelectedValuesList();

        if (id.isEmpty() || nombre.isEmpty() || platillosSeleccionados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Completa todos los campos y selecciona al menos un platillo");
            return;
        }

        // Crear nuevo pedido
        Pedido pedido = new Pedido(id, nombre);

        // Agregar los platillos seleccionados como objetos Platillo
        for (String nombrePlatillo : platillosSeleccionados) {
            for (Platillo p : PlatilloController.obtenerPlatillosDisponibles()) {
                if (nombrePlatillo.contains(p.getNombre())) {
                    pedido.agregarPlatillo(p);
                }
            }
        }

        // Guardar el pedido
        PedidoController.guardarPedidos(listaPedidos); // por si deseas recargar antes
        listaPedidos.add(pedido);
        PedidoController.guardarPedidos(listaPedidos);

        JOptionPane.showMessageDialog(this, "Pedido enviado a cocina correctamente");

        // Limpiar campos
        txt_IdPedido.setText("");
        txtNombreCliente.setText("");
        listaPlatillos.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_volver = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txt_IdPedido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPlatillos = new javax.swing.JList<>();
        btn_EnviarACocina = new javax.swing.JButton();
        btn_Agregar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListCarrito = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        btn_Agregar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel2.setBackground(new java.awt.Color(19, 70, 134));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 244, 227));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TOMAR PEDIDO");

        jPanel4.setBackground(new java.awt.Color(19, 70, 134));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 178, 26), 2, true));

        btn_volver.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btn_volver.setForeground(new java.awt.Color(254, 178, 26));
        btn_volver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_volver.setText("VOLVER");
        btn_volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_volverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_volver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(255, 255, 255)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(387, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        txtNombreCliente.setBackground(new java.awt.Color(242, 242, 242));
        txtNombreCliente.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        txtNombreCliente.setForeground(new java.awt.Color(237, 63, 39));
        txtNombreCliente.setText("Nombre del Cliente");
        txtNombreCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreClienteMouseClicked(evt);
            }
        });

        txt_IdPedido.setBackground(new java.awt.Color(242, 242, 242));
        txt_IdPedido.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        txt_IdPedido.setForeground(new java.awt.Color(237, 63, 39));
        txt_IdPedido.setText("ID del Pedido");
        txt_IdPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_IdPedidoMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(237, 63, 39));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PLATILLOS");

        listaPlatillos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaPlatillos);

        btn_EnviarACocina.setBackground(new java.awt.Color(254, 178, 26));
        btn_EnviarACocina.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_EnviarACocina.setForeground(new java.awt.Color(237, 63, 39));
        btn_EnviarACocina.setText("Enviar a cocina");
        btn_EnviarACocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EnviarACocinaActionPerformed(evt);
            }
        });

        btn_Agregar.setBackground(new java.awt.Color(254, 178, 26));
        btn_Agregar.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_Agregar.setForeground(new java.awt.Color(237, 63, 39));
        btn_Agregar.setText("Agregar");
        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });

        jListCarrito.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListCarrito);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(237, 63, 39));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Orden");

        btn_Agregar1.setBackground(new java.awt.Color(254, 178, 26));
        btn_Agregar1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_Agregar1.setForeground(new java.awt.Color(237, 63, 39));
        btn_Agregar1.setText("Eliminar");
        btn_Agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Agregar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1)
                            .addComponent(btn_Agregar, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))
                        .addGap(111, 111, 111)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_Agregar1)
                                    .addComponent(txt_IdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btn_EnviarACocina, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btn_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(423, 423, 423)
                                .addComponent(btn_EnviarACocina, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Agregar1)
                                .addGap(18, 18, 18)
                                .addComponent(txt_IdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EnviarACocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EnviarACocinaActionPerformed
    
    String cliente = txtNombreCliente.getText().trim();

    if (cliente.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el nombre del cliente");
        return;
    }

    
    if (modeloCarrito.isEmpty()) {
        JOptionPane.showMessageDialog(this, "La orden esta vacia. agregue platillos");
        return;
    }

   
    String id = PedidoController.generarNuevoId();

   
    Pedido nuevo = new Pedido(id, cliente);

   
    List<Platillo> disponibles = PlatilloController.obtenerPlatillosDisponibles();

    for (int i = 0; i < modeloCarrito.size(); i++) {
        String texto = modeloCarrito.get(i); 

        for (Platillo p : disponibles) {
            if (texto.contains(p.getNombre())) {
                nuevo.agregarPlatillo(p);
                break;
            }
        }
    }

    
    PedidoController.agregarPedido(nuevo);

    JOptionPane.showMessageDialog(this,
        "Pedido enviado a cocina exitosamente.\nID: " + id);

    
    modeloCarrito.clear();
    txtNombreCliente.setText("Nombre del Cliente");
    }//GEN-LAST:event_btn_EnviarACocinaActionPerformed

    private void btn_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_volverMouseClicked
        new VentanaEmpleado(empleado).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_volverMouseClicked

    private void txt_IdPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_IdPedidoMouseClicked
        if (txt_IdPedido.getText().equals("ID del Pedido")){
            txt_IdPedido.setText("");
        }
        if(txtNombreCliente.getText().isEmpty()){
            txtNombreCliente.setText("Nombre del Cliente");
        }
    }//GEN-LAST:event_txt_IdPedidoMouseClicked

    private void txtNombreClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreClienteMouseClicked
        if(txt_IdPedido.getText().isEmpty()){
            txt_IdPedido.setText("ID del Pedido");
        }
        if(txtNombreCliente.getText().equals("Nombre del Cliente")){
            txtNombreCliente.setText("");
        }
    }//GEN-LAST:event_txtNombreClienteMouseClicked

    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed
    
    
    List<String> seleccion = listaPlatillos.getSelectedValuesList();

    if (seleccion.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Selecciona al menos un platillo");
        return;
    }

    
    for (String platillo : seleccion) {
        modeloCarrito.addElement(platillo);
    }

    listaPlatillos.clearSelection();
    }//GEN-LAST:event_btn_AgregarActionPerformed

    private void btn_Agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Agregar1ActionPerformed
        int index = jListCarrito.getSelectedIndex();

    if (index == -1) {
        JOptionPane.showMessageDialog(this,
                "Selecciona un platillo del carrito para eliminarlo");
        return;
    }

    // Eliminar el seleccionado
    modeloCarrito.remove(index);

    JOptionPane.showMessageDialog(this, "Platillo eliminado del carrito");
    }//GEN-LAST:event_btn_Agregar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TomarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TomarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TomarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TomarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TomarPedidos(new Empleado("0000","Empleado","1234")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton btn_Agregar1;
    private javax.swing.JButton btn_EnviarACocina;
    private javax.swing.JLabel btn_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jListCarrito;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listaPlatillos;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txt_IdPedido;
    // End of variables declaration//GEN-END:variables
}
