/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant_chef_app.view;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import restaurant_chef_app.Controller.PedidoController;
import restaurant_chef_app.Controller.PlatilloController;
import restaurant_chef_app.clases.Pedido;
import restaurant_chef_app.clases.Platillo;

/**
 *
 * @author Usuario
 */
public class TomarPedidos extends javax.swing.JFrame {

    private List<Pedido> listaPedidos;

    public TomarPedidos() {
        initComponents();
        setLocationRelativeTo(null);

        List<Platillo> menu = PlatilloController.obtenerPlatillosDisponibles();
        DefaultListModel<String> modelo = new DefaultListModel<>();

        String categoriaActual = "";

        for (Platillo p : menu) {
            if (!p.getCategoria().equals(categoriaActual)) {
                categoriaActual = p.getCategoria();
                modelo.addElement("---- " + categoriaActual.toUpperCase() + " ----");
            }
            modelo.addElement("• " + p.getNombre() + " ($" + p.getPrecio() + ")");
        }

        listaPlatillos.setModel(modelo);
        listaPedidos = PedidoController.cargarPedidos();
    }

    private void enviarPedido() {
        String id = txtIdPedido.getText();
        String nombre = txtNombreCliente.getText();
        List<String> platillosSeleccionados = listaPlatillos.getSelectedValuesList();

        if (id.isEmpty() || nombre.isEmpty() || platillosSeleccionados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Completa todos los campos y selecciona al menos un platillo");
            return;
        }

        // Crear nuevo pedido
        Pedido pedido = new Pedido(id, nombre);

        // Agregar los platillos seleccionados como objetos Platillo
        for (String nombrePlatillo : platillosSeleccionados) {
            for (Platillo p : PlatilloController.obtenerPlatillosDisponibles()) {
                if (nombrePlatillo.contains(p.getNombre())) {
                    pedido.agregarPlatillo(p);
                }
            }
        }

        // Guardar el pedido
        PedidoController.guardarPedidos(listaPedidos); // por si deseas recargar antes
        listaPedidos.add(pedido);
        PedidoController.guardarPedidos(listaPedidos);

        JOptionPane.showMessageDialog(this, "Pedido enviado a cocina correctamente");

        // Limpiar campos
        txtIdPedido.setText("");
        txtNombreCliente.setText("");
        listaPlatillos.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtIdPedido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPlatillos = new javax.swing.JList<>();
        btn_EnviarACocina1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel2.setBackground(new java.awt.Color(19, 70, 134));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 244, 227));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TOMAR PEDIDO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(434, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        txtNombreCliente.setBackground(new java.awt.Color(242, 242, 242));
        txtNombreCliente.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        txtNombreCliente.setForeground(new java.awt.Color(237, 63, 39));
        txtNombreCliente.setText("Nombre del Cliente");
        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });

        txtIdPedido.setBackground(new java.awt.Color(242, 242, 242));
        txtIdPedido.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        txtIdPedido.setForeground(new java.awt.Color(237, 63, 39));
        txtIdPedido.setText("ID del Pedido");
        txtIdPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPedidoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(237, 63, 39));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PLATILLOS");

        listaPlatillos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaPlatillos);

        btn_EnviarACocina1.setBackground(new java.awt.Color(254, 178, 26));
        btn_EnviarACocina1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_EnviarACocina1.setForeground(new java.awt.Color(237, 63, 39));
        btn_EnviarACocina1.setText("Enviar a cocina");
        btn_EnviarACocina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EnviarACocina1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(btn_EnviarACocina1))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtIdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btn_EnviarACocina1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void txtIdPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPedidoActionPerformed

    private void btn_EnviarACocina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EnviarACocina1ActionPerformed
        String id = txtIdPedido.getText().trim();
        String nombre = txtNombreCliente.getText().trim();

        if (id.isEmpty() || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el ID y el nombre del cliente");
            return;
        }

        // Obtener platillos seleccionados
        List<String> seleccion = listaPlatillos.getSelectedValuesList();

        if (seleccion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un platillo");
            return;
        }

        // Crear el pedido con estado "En cocina"
        Pedido pedido = new Pedido(id, nombre);
        pedido.setEstado("En cocina");

        // Buscar objetos Platillo según el nombre
        for (String linea : seleccion) {
            if (!linea.startsWith("----")) { // Ignorar líneas de categoría
                try {
                    String nombrePlatillo = linea.substring(
                            linea.indexOf("• ") + 2,
                            linea.indexOf(" ($")
                    );

                    for (Platillo p : PlatilloController.obtenerPlatillosDisponibles()) {
                        if (nombrePlatillo.equals(p.getNombre())) {
                            pedido.agregarPlatillo(p);
                            break;
                        }
                    }
                } catch (Exception e) {
                    System.err.println("⚠️ Error al procesar línea: " + linea);
                }
            }
        }

        // Agregar y guardar pedido
        listaPedidos.add(pedido);
        PedidoController.guardarPedidos(listaPedidos);

        JOptionPane.showMessageDialog(this, "✅ Pedido enviado a cocina correctamente");

        // Limpiar campos
        txtIdPedido.setText("");
        txtNombreCliente.setText("");
        listaPlatillos.clearSelection();
    }//GEN-LAST:event_btn_EnviarACocina1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TomarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TomarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TomarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TomarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TomarPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_EnviarACocina1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaPlatillos;
    private javax.swing.JTextField txtIdPedido;
    private javax.swing.JTextField txtNombreCliente;
    // End of variables declaration//GEN-END:variables
}
