/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant_chef_app.view;

import java.util.List;
import javax.swing.DefaultListModel;
import restaurant_chef_app.Controller.*;
import restaurant_chef_app.clases.*;

/**
 *
 * @author Sebastian JB
 */
public class VerEmpleadosAdministrador extends javax.swing.JFrame {

    public Empleado empleado;
    public Cocinero cocinero;
    public DefaultListModel<String> modelo;

    /**
     * Creates new form VerEmpleados
     */
    public VerEmpleadosAdministrador() {
        initComponents();
        setLocationRelativeTo(null);

        modelo = obtenerTodosLosUsuariosParaLista();
        listaUsuarios.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaUsuarios = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_idDescripcion = new javax.swing.JTextField();
        txt_nombreDescripcion = new javax.swing.JTextField();
        txt_categoriaDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbx_Roles = new javax.swing.JComboBox<>();
        btn_EditarUsuario = new javax.swing.JButton();
        btn_EliminarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(237, 63, 39));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 178, 26), 3, true));

        listaUsuarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "ID EMPLEADO", "NOMBRE", "ROL" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaUsuarios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaUsuariosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaUsuarios);

        jPanel1.setBackground(new java.awt.Color(237, 63, 39));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 244, 227), 3), "DATOS DEL EMPLEADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 12), new java.awt.Color(253, 244, 227))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 244, 227));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(253, 244, 227));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("NOMBRE");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(253, 244, 227));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("CONTRASEÑA");

        txt_idDescripcion.setEditable(false);
        txt_idDescripcion.setBackground(new java.awt.Color(254, 178, 26));
        txt_idDescripcion.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        txt_idDescripcion.setForeground(new java.awt.Color(253, 244, 227));

        txt_nombreDescripcion.setBackground(new java.awt.Color(254, 178, 26));
        txt_nombreDescripcion.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        txt_nombreDescripcion.setForeground(new java.awt.Color(253, 244, 227));

        txt_categoriaDescripcion.setBackground(new java.awt.Color(254, 178, 26));
        txt_categoriaDescripcion.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        txt_categoriaDescripcion.setForeground(new java.awt.Color(253, 244, 227));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(253, 244, 227));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("TIPO DE USUARIO");

        cbx_Roles.setBackground(new java.awt.Color(254, 178, 26));
        cbx_Roles.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        cbx_Roles.setForeground(new java.awt.Color(253, 244, 227));
        cbx_Roles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ROL", "EMPLEADO", "COCINERO" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_idDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(txt_categoriaDescripcion)
                    .addComponent(txt_nombreDescripcion)
                    .addComponent(cbx_Roles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_idDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombreDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_categoriaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cbx_Roles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btn_EditarUsuario.setBackground(new java.awt.Color(19, 70, 134));
        btn_EditarUsuario.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btn_EditarUsuario.setForeground(new java.awt.Color(253, 244, 227));
        btn_EditarUsuario.setText("EDITAR");
        btn_EditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarUsuarioActionPerformed(evt);
            }
        });

        btn_EliminarUsuario.setBackground(new java.awt.Color(19, 70, 134));
        btn_EliminarUsuario.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btn_EliminarUsuario.setForeground(new java.awt.Color(253, 244, 227));
        btn_EliminarUsuario.setText("ELIMINAR");
        btn_EliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_EliminarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_EditarUsuario)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_EditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_EliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaUsuariosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaUsuariosValueChanged
        // TODO add your handling code here:
        if (evt.getValueIsAdjusting() || listaUsuarios.getSelectedValue() == null) {
            return;
        }

        String seleccion = listaUsuarios.getSelectedValue().trim();
        
        if (seleccion.startsWith("===") || seleccion.isEmpty() || seleccion.equals("No hay usuarios registrados")) {
            return;
        }

        int selectedIndex = listaUsuarios.getSelectedIndex();
        
        String seccion = determinarSeccion(selectedIndex);

        if (seleccion.startsWith("ID:")) {
            String[] partes = seleccion.split(" - ");
            if (partes.length >= 1) {
                String id = partes[0].replace("ID:", "").trim();
                buscarUsuarioPorIdYSeccion(id, seccion);
            }
        }
    }//GEN-LAST:event_listaUsuariosValueChanged

    private void btn_EditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarUsuarioActionPerformed
        // TODO add your handling code here:
        if (listaUsuarios.getSelectedValue() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un usuario para editar");
            return;
        }

        String id = txt_idDescripcion.getText().trim();
        String nombre = txt_nombreDescripcion.getText().trim();
        String contraseña = txt_categoriaDescripcion.getText().trim();
        String tipo = cbx_Roles.getSelectedItem().toString();

        if (id.isEmpty() || nombre.isEmpty() || contraseña.isEmpty() || tipo.equals("ROL")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Complete todos los campos");
            return;
        }

        boolean exito = false;

        switch (tipo) {
            case "EMPLEADO":
                exito = EmpleadoController.editarEmpleado(id, nombre, contraseña);
                break;
            case "COCINERO":
                exito = CocineroController.editarCocinero(id, nombre, contraseña);
                break;
        }

        if (exito) {
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario editado correctamente");
            
            modelo = obtenerTodosLosUsuariosParaLista();
            listaUsuarios.setModel(modelo);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al editar usuario");
        }
    }//GEN-LAST:event_btn_EditarUsuarioActionPerformed

    private void btn_EliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarUsuarioActionPerformed
        // TODO add your handling code here:
        if (listaUsuarios.getSelectedValue() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un usuario para eliminar");
            return;
        }

        String id = txt_idDescripcion.getText().trim();
        String tipo = cbx_Roles.getSelectedItem().toString();

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar este usuario?", "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            boolean exito = false;

            switch (tipo) {
                case "EMPLEADO":
                    exito = EmpleadoController.eliminarEmpleado(id);
                    break;
                case "COCINERO":
                    exito = CocineroController.eliminarCocinero(id);
                    break;
            }

            if (exito) {
                javax.swing.JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente");
                
                modelo = obtenerTodosLosUsuariosParaLista();
                listaUsuarios.setModel(modelo);
                limpiarCampos();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar usuario");
            }
        }
    }//GEN-LAST:event_btn_EliminarUsuarioActionPerformed

    private void buscarUsuarioPorIdYSeccion(String id, String seccion) {
        switch (seccion) {

            case "empleado":
                List<Empleado> empleados = EmpleadoController.leerEmpleado();
                for (Empleado empleado : empleados) {
                    if (empleado.getId().equals(id)) {
                        actualizarLabels(empleado);
                        return;
                    }
                }
                break;

            case "cocinero":
                List<Cocinero> cocineros = CocineroController.leerCocinero();
                for (Cocinero cocinero : cocineros) {
                    if (cocinero.getId().equals(id)) {
                        actualizarLabels(cocinero);
                        return;
                    }
                }
                break;
        }
    }

    private String determinarSeccion(int index) {
        DefaultListModel<String> modelo = (DefaultListModel<String>) listaUsuarios.getModel();

        
        for (int i = index; i >= 0; i--) {
            String elemento = modelo.getElementAt(i);

            if (elemento.startsWith("=== EMPLEADOS ===")) {
                return "empleado";
            }
            if (elemento.startsWith("=== COCINEROS ===")) {
                return "cocinero";
            }
        }
        return "";
    }

    private void buscarUsuarioPorId(String id) {

        List<Empleado> empleados = EmpleadoController.leerEmpleado();
        for (Empleado empleado : empleados) {
            if (empleado.getId().equals(id)) {
                actualizarLabels(empleado);
                return;
            }
        }
        
        List<Cocinero> cocineros = CocineroController.leerCocinero();
        for (Cocinero cocinero : cocineros) {
            if (cocinero.getId().equals(id)) {
                actualizarLabels(cocinero);
                return;
            }
        }
    }

    private void actualizarLabels(Usuario usuario) {
        txt_idDescripcion.setText("" + usuario.getId());
        txt_nombreDescripcion.setText("" + usuario.getNombre());
        txt_categoriaDescripcion.setText("" + usuario.getContraseña());
        if (usuario.getTipo().equalsIgnoreCase("empleado")) {
            cbx_Roles.setSelectedIndex(1);
        } else if (usuario.getTipo().equalsIgnoreCase("cocinero")) {
            cbx_Roles.setSelectedIndex(2);
        } else {
            cbx_Roles.setSelectedIndex(0);
        }
    }

    private void limpiarCampos() {
        txt_idDescripcion.setText("");
        txt_nombreDescripcion.setText("");
        txt_categoriaDescripcion.setText("");
        cbx_Roles.setSelectedIndex(0);
    }

    public static DefaultListModel<String> obtenerTodosLosUsuariosParaLista() {
        DefaultListModel<String> modelo = new DefaultListModel<>();

        List<Cocinero> cocineros = CocineroController.leerCocinero();
        List<Empleado> empleados = EmpleadoController.leerEmpleado();

        modelo.addElement("=== EMPLEADOS ===");
        for (Empleado empleado : empleados) {
            modelo.addElement(" ID: " + empleado.getId() + " - " + empleado.getNombre());
        }

        modelo.addElement("");
        
        modelo.addElement("=== COCINEROS ===");
        for (Cocinero cocinero : cocineros) {
            modelo.addElement("ID: " + cocinero.getId() + " - " + cocinero.getNombre());
        }

        if (cocineros.isEmpty() && empleados.isEmpty()) {
            modelo.addElement("No hay usuarios registrados");
        }

        return modelo;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerEmpleadosAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerEmpleadosAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerEmpleadosAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerEmpleadosAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerEmpleadosAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_EditarUsuario;
    private javax.swing.JButton btn_EliminarUsuario;
    private javax.swing.JComboBox<String> cbx_Roles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaUsuarios;
    private javax.swing.JTextField txt_categoriaDescripcion;
    private javax.swing.JTextField txt_idDescripcion;
    private javax.swing.JTextField txt_nombreDescripcion;
    // End of variables declaration//GEN-END:variables
}
